import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import NavBar from "../components/NavBar";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
